import { useMemo, useState } from 'react'

type Status = 'New' | 'Needs Review' | 'Verified' | 'Pickable' | 'Assigned to Picklist' | 'Ready to Go' | 'Draft Invoice Created' | 'Out for Delivery' | 'POD Received' | 'Complete' | 'Cancelled'
type RunName = 'Unassigned' | 'Friday Run' | 'Monday Run' | 'Carryover'
type ProductKey = '473_MER'|'473_GNG'|'473_CUR'|'473_ERL'|'750_MER'|'750_GNG'|'750_CUR'|'500G_WFW'|'500G_CLV'|'500G_CCW'|'1KG_WFW'|'1KG_CLV'|'1KG_CCW'

type Order = {id:string;customer:string;source:string;status:Status;run:RunName;invoice?:string;notes:string;pricingAdjustment:boolean;pod:boolean;manualReview:boolean;qty:Record<ProductKey,number>;pricingNotes?:string}

const PRODUCTS:{key:ProductKey;name:string;group:string;casePack:number;casePrice:number}[]=[
{key:'473_MER',name:'473 mL Mermaid Tears',group:'473 mL',casePack:15,casePrice:96},{key:'473_GNG',name:'473 mL Ginger Splash',group:'473 mL',casePack:15,casePrice:98},{key:'473_CUR',name:'473 mL Currantly Hip',group:'473 mL',casePack:15,casePrice:99},{key:'473_ERL',name:'473 mL Earl Grey',group:'473 mL',casePack:15,casePrice:101},
{key:'750_MER',name:'750 mL Mermaid Tears',group:'750 mL',casePack:12,casePrice:102},{key:'750_GNG',name:'750 mL Ginger Splash',group:'750 mL',casePack:12,casePrice:104},{key:'750_CUR',name:'750 mL Currantly Hip',group:'750 mL',casePack:12,casePrice:105},
{key:'500G_WFW',name:'500g Wildflower Honey',group:'500g Honey',casePack:12,casePrice:90},{key:'500G_CLV',name:'500g Clover Honey',group:'500g Honey',casePack:12,casePrice:92},{key:'500G_CCW',name:'500g Creamed Honey',group:'500g Honey',casePack:12,casePrice:95},
{key:'1KG_WFW',name:'1kg Wildflower Honey',group:'1kg Honey',casePack:12,casePrice:140},{key:'1KG_CLV',name:'1kg Clover Honey',group:'1kg Honey',casePack:12,casePrice:145},{key:'1KG_CCW',name:'1kg Creamed Honey',group:'1kg Honey',casePack:12,casePrice:148},
]
const STATUSES:Status[]=['New','Needs Review','Verified','Pickable','Assigned to Picklist','Ready to Go','Draft Invoice Created','Out for Delivery','POD Received','Complete','Cancelled']
const customers=['Maple Street Market','Coastal Pantry','Hilltop Foods','Birch & Barrel','Harbor Deli','Sunrise Grocer','Valley Farm Shop','Northline Co-op','Evergreen Kitchen','Honeycomb Provisions']
const emptyQty=()=>Object.fromEntries(PRODUCTS.map(p=>[p.key,0])) as Record<ProductKey,number>
const makeOrder=(id:number,c:string,status:Status,run:RunName,notes:string,p=false,inv?:string,pod=false):Order=>({id:`ORD-${id}`,customer:c,source:id%2?'Google Form':'Phone',status,run,invoice:inv,notes,pricingAdjustment:p,pod,manualReview:notes.toLowerCase().includes('keg'),qty:{...emptyQty(),473_MER:id%3,750_GNG:id%2,500G_WFW:id%4,1KG_CLV:id%2},pricingNotes:p?'Seasonal promo requested':''})

const seed:Order[]=[makeOrder(1001,customers[0],'New','Unassigned','Needs 3kg in notes',true),makeOrder(1002,customers[1],'Needs Review','Unassigned','Wants keg quote'),makeOrder(1003,customers[2],'Verified','Unassigned',''),makeOrder(1004,customers[3],'Pickable','Unassigned',''),makeOrder(1005,customers[4],'Assigned to Picklist','Friday Run','Front door'),makeOrder(1006,customers[5],'Ready to Go','Friday Run','AM drop'),makeOrder(1007,customers[6],'Draft Invoice Created','Monday Run','',false,'FB-DRAFT-1042'),makeOrder(1008,customers[7],'Out for Delivery','Monday Run','',false,'FB-DRAFT-1043'),makeOrder(1009,customers[8],'POD Received','Carryover','Signed by Sam',false,'FB-DRAFT-1044',true),makeOrder(1010,customers[9],'Complete','Carryover','Delivered last week',false,'FB-DRAFT-1045',true),makeOrder(1011,customers[0],'Pickable','Unassigned','Manual custom blend',true),makeOrder(1012,customers[1],'Cancelled','Unassigned','Store renovation')]

export default function App(){
const [tab,setTab]=useState<'board'|'runs'|'print'>('board'); const [orders,setOrders]=useState(seed); const [selected,setSelected]=useState<string[]>([]); const [displayStatuses,setDisplay]=useState<Status[]>(STATUSES.filter(s=>s!=='Cancelled')); const [totalStatuses,setTotal]=useState<Status[]>(['Pickable','Assigned to Picklist','Ready to Go']); const [detail,setDetail]=useState<Order|null>(null); const [msg,setMsg]=useState(''); const [printRun,setPrintRun]=useState<RunName>('Friday Run');
const filtered=orders.filter(o=>displayStatuses.includes(o.status));
const totals=useMemo(()=>{const source=orders.filter(o=>totalStatuses.includes(o.status)); const cases=emptyQty(); let revenue=0; source.forEach(o=>PRODUCTS.forEach(p=>{cases[p.key]+=o.qty[p.key]; revenue+=o.qty[p.key]*p.casePrice})); return {cases,revenue,count:source.length}},[orders,totalStatuses]);
const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
const update=(ids:string[],patch:Partial<Order>)=>setOrders(o=>o.map(x=>ids.includes(x.id)?{...x,...patch}:x));
const makeInvoice=(ids:string[])=>{let n=1040; setOrders(o=>o.map(x=>ids.includes(x.id)?{...x,status:'Draft Invoice Created',invoice:x.invoice??`FB-DRAFT-${++n}`}:x)); setMsg(`Created: ${ids.length} | Failed: 0 | Needs Review: 0`)}
const grouped=(run:RunName)=>orders.filter(o=>run==='Unassigned'?o.status==='Pickable'&&o.run==='Unassigned':o.run===run)
const move=(id:string,run:RunName)=>setOrders(o=>o.map(x=>x.id===id?{...x,run,status:run==='Unassigned'?'Pickable':'Assigned to Picklist'}:x))
return <div className='app'><h1>Wholesale Order Board (POC)</h1><div className='tabs'>{[['board','Order Board'],['runs','Picklist / Delivery Runs'],['print','Print Preview']].map(([k,l])=><button key={k} onClick={()=>setTab(k as any)}>{l}</button>)}</div>{msg&&<p>{msg}</p>}
{tab==='board'&&<>
<div className='panel'><button onClick={()=>setOrders([{id:`ORD-${Date.now()}`,customer:customers[0],source:'Google Form',status:'New',run:'Unassigned',notes:'',pricingAdjustment:false,pod:false,manualReview:false,qty:emptyQty()},...orders])}>+ New Order</button>
<select onChange={e=>update(selected,{status:e.target.value as Status})}><option>Bulk Status</option>{STATUSES.map(s=><option key={s}>{s}</option>)}</select>
<button onClick={()=>update(selected,{status:'Verified'})}>Mark selected Verified</button><button onClick={()=>update(selected,{status:'Pickable'})}>Move selected to Pickable</button><button onClick={()=>update(selected,{status:'Assigned to Picklist',run:'Friday Run'})}>Assign selected to Picklist</button><button onClick={()=>makeInvoice(selected)}>Create Fake Draft Invoices</button><button onClick={()=>update(selected,{status:'Out for Delivery'})}>Mark selected Out for Delivery</button><button onClick={()=>update(selected,{status:'POD Received',pod:true})}>Mark selected POD Received</button><button onClick={()=>update(selected,{status:'Complete'})}>Mark selected Complete</button></div>
<div className='filters'><b>Display Statuses:</b>{STATUSES.map(s=><label key={s}><input type='checkbox' checked={displayStatuses.includes(s)} onChange={()=>setDisplay(x=>x.includes(s)?x.filter(v=>v!==s):[...x,s])}/>{s}</label>)}</div>
<div className='filters'><b>Totals Statuses:</b>{STATUSES.map(s=><label key={s+'t'}><input type='checkbox' checked={totalStatuses.includes(s)} onChange={()=>setTotal(x=>x.includes(s)?x.filter(v=>v!==s):[...x,s])}/>{s}</label>)}</div>
<table><thead><tr><th></th><th>Customer</th><th>Source</th><th>Status</th><th>Run</th><th>Invoice</th>{PRODUCTS.map(p=><th key={p.key}>{p.key}</th>)}<th>Notes</th><th>Pricing Adj</th><th>POD</th></tr></thead><tbody>{filtered.map(o=><tr key={o.id} onClick={()=>setDetail(o)}><td><input type='checkbox' checked={selected.includes(o.id)} onChange={e=>{e.stopPropagation();toggle(o.id)}}/></td><td>{o.customer}</td><td>{o.source}</td><td>{o.status}</td><td>{o.run}</td><td>{o.invoice||'-'}</td>{PRODUCTS.map(p=><td key={p.key}><input type='number' value={o.qty[p.key]} min={0} onClick={e=>e.stopPropagation()} onChange={e=>setOrders(prev=>prev.map(x=>x.id===o.id?{...x,qty:{...x.qty,[p.key]:Number(e.target.value)}}:x))}/></td>)}<td>{o.notes}</td><td><input type='checkbox' checked={o.pricingAdjustment} onClick={e=>e.stopPropagation()} onChange={()=>setOrders(prev=>prev.map(x=>x.id===o.id?{...x,pricingAdjustment:!x.pricingAdjustment}:x))}/></td><td>{o.pod?'Received':'Pending'}</td></tr>)}</tbody></table>
<div className='totals'><h3>Totals (selected statuses only)</h3><p>Orders in totals: {totals.count} | Estimated revenue: ${totals.revenue.toFixed(2)}</p><div className='grid'>{PRODUCTS.map(p=><div key={p.key}><b>{p.key}</b><div>Cases: {totals.cases[p.key]}</div><div>Units: {totals.cases[p.key]*p.casePack}</div></div>)}</div></div>
</>}
{tab==='runs'&&<div className='runs'>{(['Unassigned','Friday Run','Monday Run','Carryover'] as RunName[]).map(r=><div key={r} className='run'><h3>{r==='Unassigned'?'Pickable Orders':r}</h3>{r!=='Unassigned'&&<><button onClick={()=>update(grouped(r).map(o=>o.id),{status:'Ready to Go'})}>Mark run Ready to Go</button><button onClick={()=>makeInvoice(grouped(r).map(o=>o.id))}>Create run draft invoices</button><button onClick={()=>update(grouped(r).map(o=>o.id),{status:'Out for Delivery'})}>Mark run Out for Delivery</button></>}{grouped(r).map((o,i)=><div key={o.id} className='card'><div>{i+1}. {o.customer} ({o.status}) {o.invoice||''}</div><div>{PRODUCTS.filter(p=>o.qty[p.key]>0).map(p=>`${p.key}:${o.qty[p.key]}`).join(', ')||'No items'}</div><small>{o.notes}</small><div><button onClick={()=>move(o.id,'Unassigned')}>To Pickable</button><button onClick={()=>move(o.id,'Friday Run')}>Friday</button><button onClick={()=>move(o.id,'Monday Run')}>Monday</button><button onClick={()=>move(o.id,'Carryover')}>Carryover</button><button disabled={i===0} onClick={()=>setOrders(prev=>{const arr=[...prev]; const ids=grouped(r).map(x=>x.id); const idx=ids.indexOf(o.id); const a=arr.findIndex(x=>x.id===ids[idx]); const b=arr.findIndex(x=>x.id===ids[idx-1]); [arr[a],arr[b]]=[arr[b],arr[a]]; return arr})}>↑</button><button disabled={i===grouped(r).length-1} onClick={()=>setOrders(prev=>{const arr=[...prev]; const ids=grouped(r).map(x=>x.id); const idx=ids.indexOf(o.id); const a=arr.findIndex(x=>x.id===ids[idx]); const b=arr.findIndex(x=>x.id===ids[idx+1]); [arr[a],arr[b]]=[arr[b],arr[a]]; return arr})}>↓</button></div></div>)}</div>)}</div>}
{tab==='print'&&<div><h2>Print Preview</h2><select value={printRun} onChange={e=>setPrintRun(e.target.value as RunName)}><option>Friday Run</option><option>Monday Run</option><option>Carryover</option></select><p>Delivery date: __________</p><table><thead><tr><th>#</th><th>Store</th><th>Invoice</th><th>Products</th><th>Notes</th><th>POD</th></tr></thead><tbody>{grouped(printRun).map((o,i)=><tr key={o.id}><td>{i+1}</td><td>{o.customer}</td><td>{o.invoice||'Pending'}</td><td>{PRODUCTS.map(p=>o.qty[p.key]?`${p.key}:${o.qty[p.key]}`:'').filter(Boolean).join(', ')}</td><td>{o.notes}</td><td>{o.pod?'Received':'Pending'}</td></tr>)}</tbody></table></div>}
{detail&&<div className='modal' onClick={()=>setDetail(null)}><div className='modalCard' onClick={e=>e.stopPropagation()}><h3>{detail.customer}</h3><p>Source: {detail.source}</p><p>Status: {detail.status}</p><p>Picklist assignment: {detail.run}</p><p>Pricing adjustment needed: {detail.pricingAdjustment?'Yes':'No'}</p><p>Pricing notes: {detail.pricingNotes||'None'}</p><p>Invoice provider: FreshBooks (placeholder only)</p><p>External invoice number: {detail.invoice||'Not created'}</p><p>POD status: {detail.pod?'Received':'Pending'}</p><p>Submitted By: Jordan @ Store (placeholder)</p><p>Best Order Contact: Alex Rivera (placeholder)</p><p>Manual Review: {detail.manualReview?'Yes':'No'}</p></div></div>}
</div>
}
